### ISSUE TITLE
不想集成推送功能，但集成环信即时通讯 SDK 3.2.0 版本时报找不到华为和小米推送相关类，而且在聊天界面监听不到新消息

### ISSUE THREAD

**Issue by bingoogolapple** [lzan13/EaseChat#1]
@lzan13 不想集成推送功能，但集成环信即时通讯 SDK 3.2.0 版本时报找不到华为和小米推送相关类，而且在聊天界面监听不到新消息，这个问题已经卡了两天了，麻烦看到后回复一下，谢谢。

[这是报错项目源码的仓库地址](https://github.com/bingoogolapple/BGAScaffolding-Android)

```
11-11 01:12:52.049 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: java.lang.ClassNotFoundException: com.xiaomi.mipush.sdk.MiPushClient
11-11 01:12:52.049 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.Class.classForName(Native Method)
11-11 01:12:52.049 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.Class.forName(Class.java:324)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.Class.forName(Class.java:285)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at com.hyphenate.chat.EMPushHelper.checkAvailablePushService(Unknown Source)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at com.hyphenate.chat.EMClient.checkPushAvailable(Unknown Source)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at com.hyphenate.chat.EMClient$6.run(Unknown Source)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.xiaomi.mipush.sdk.MiPushClient" on path: DexPathList[[zip file "/data/app/cn.bingoogolapple.scaffolding.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.bingoogolapple.scaffolding.demo-1/lib/arm, /data/app/cn.bingoogolapple.scaffolding.demo-1/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: 	... 9 more
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.xiaomi.mipush.sdk.MiPushClient
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.Class.classForName(Native Method)
11-11 01:12:52.050 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-11 01:12:52.051 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-11 01:12:52.051 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-11 01:12:52.051 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: 		... 10 more
11-11 01:12:52.051 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
11-11 01:12:52.052 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: java.lang.ClassNotFoundException: com.huawei.android.pushagent.api.PushManager
11-11 01:12:52.052 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.Class.classForName(Native Method)
11-11 01:12:52.052 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.Class.forName(Class.java:324)
11-11 01:12:52.052 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.Class.forName(Class.java:285)
11-11 01:12:52.052 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at com.hyphenate.chat.EMPushHelper.checkAvailablePushService(Unknown Source)
11-11 01:12:52.052 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at com.hyphenate.chat.EMClient.checkPushAvailable(Unknown Source)
11-11 01:12:52.052 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at com.hyphenate.chat.EMClient$6.run(Unknown Source)
11-11 01:12:52.052 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-11 01:12:52.052 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.huawei.android.pushagent.api.PushManager" on path: DexPathList[[zip file "/data/app/cn.bingoogolapple.scaffolding.demo-1/base.apk"],nativeLibraryDirectories=[/data/app/cn.bingoogolapple.scaffolding.demo-1/lib/arm, /data/app/cn.bingoogolapple.scaffolding.demo-1/base.apk!/lib/armeabi, /vendor/lib, /system/lib]]
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: 	... 9 more
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.huawei.android.pushagent.api.PushManager
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.Class.classForName(Native Method)
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: 		... 10 more
11-11 01:12:52.053 4922-4988/cn.bingoogolapple.scaffolding.demo W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by lzan13** [comment]
这个错误是已经 try cache过的，只是 sdk 检测是否有小米和华为 sdk，
关于聊天界面兼听不到消息问题，检查下是否注册了消息监听
